# Generated by Django 4.2.7 on 2024-01-10 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='abc', max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=22, unique=True)),
                ('complain_title', models.CharField(max_length=300)),
                ('complain_description', models.TextField()),
                ('complain_image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=200, null=True)),
                ('complain_status', models.PositiveBigIntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Responsed'), (4, 'Rejected')], default=1)),
                ('purpose', models.PositiveBigIntegerField(choices=[(1, 'Export'), (2, 'Import'), (3, 'Domestic'), (4, 'Regulations'), (5, 'Others')], default=None)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_complain', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ManyToManyField(default=None, related_name='is_available', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ComplainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=60, unique=True)),
                ('nepali_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplainSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=60, unique=True)),
                ('nepali_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_description', models.TextField()),
                ('response_image', models.ImageField(null=True, upload_to='')),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='management.complain')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='complain',
            name='complain_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_complain', to='management.complaincategory'),
        ),
        migrations.AddField(
            model_name='complain',
            name='complain_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complain_sub_category', to='management.complainsubcategory'),
        ),
        migrations.AddField(
            model_name='complain',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_complains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complain',
            name='is_anonymous',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.anonymoususer'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('communication_creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain_communication', to='management.complain')),
            ],
        ),
    ]
